/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ringdroid_soundfile_NativeMP3Decoder */

#ifndef _Included_com_ringdroid_soundfile_NativeMP3Decoder
#define _Included_com_ringdroid_soundfile_NativeMP3Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_audio_io_NativeMP3Decoder
 * Method:    openFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_openFile
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_readNextFrame
  (JNIEnv *env, jobject obj, jint handle);

JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_readSamplesAll
  (JNIEnv *env, jobject obj, jint handle);

/*
 * Class:     com_badlogic_audio_io_NativeMP3Decoder
 * Method:    readSamples
 * Signature: (ILjava/nio/FloatBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_readSamples__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_audio_io_NativeMP3Decoder
 * Method:    readSamples
 * Signature: (ILjava/nio/ShortBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_readSamples__ILjava_nio_ShortBuffer_2I
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_audio_io_NativeMP3Decoder
 * Method:    closeFile
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_closeFile
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_getSize
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_getFrameLen
  (JNIEnv *, jobject, jint);

JNIEXPORT jlong JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_getOffset
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_getBitRate
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_getSampleRate
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_getNchannels
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_ringdroid_soundfile_NativeMP3Decoder_getSamplesPerFrame
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
